use crate::fetch::{LUCIDE_COMMIT, LUCIDE_VERSION};
use crate::parse::Icon;

use crate::emit_docs::{preview_img, related_icon_links, widget_container};

use dioxus_rsx::{Attribute, AttributeName, AttributeValue, BodyNode, HotLiteral, PartialExpr};
use proc_macro2::{Ident, Span};

pub fn emit_component(icon: &Icon, related_icons: &[&Icon]) -> String {
    let mut output = String::new();

    output.push_str(&format!(
        "// @generated by dioxus-icons-codegen from Lucide v{LUCIDE_VERSION} ({LUCIDE_COMMIT}). Do not edit.\n"
    ));
    output.push_str("// Lucide icons are licensed under ISC. See LICENSE-LUCIDE.\n\n");
    output.push_str("use dioxus::prelude::*;\n");
    output.push('\n');

    let props_name = format!("{}Props", icon.component);

    output.push_str("#[doc(hidden)]\n");
    output.push_str("#[derive(Clone, PartialEq, Props)]\n");
    output.push_str(&format!("pub struct {props_name} {{\n"));
    output.push_str("    #[props(default = 24)]\n");
    output.push_str("    pub size: u32,\n");
    output.push_str("    #[props(into, default = \"currentColor\")]\n");
    output.push_str("    pub color: std::borrow::Cow<'static, str>,\n");
    output.push_str("    #[props(default = 2)]\n");
    output.push_str("    pub stroke_width: u32,\n");
    output.push_str("    #[props(into, default = \"round\")]\n");
    output.push_str("    pub stroke_linecap: std::borrow::Cow<'static, str>,\n");
    output.push_str("    #[props(into, default = \"round\")]\n");
    output.push_str("    pub stroke_linejoin: std::borrow::Cow<'static, str>,\n");
    output.push_str("    #[props(into, default = \"\")]\n");
    output.push_str("    pub class: std::borrow::Cow<'static, str>,\n");
    output.push_str("}\n\n");

    push_doc_comment(&mut output, icon, related_icons);
    output.push_str("#[doc = include_str!(\"../../../rustdoc-header.html\")]\n");
    output.push_str("#[allow(non_snake_case)]\n");
    output.push_str("#[allow(clippy::too_many_lines)]\n");
    output.push_str(&format!(
        "pub fn {}(props: {props_name}) -> Element {{\n",
        icon.component
    ));
    output.push_str(&format!(
        "    let {props_name} {{\n        size,\n        color,\n        stroke_width,\n        stroke_linecap,\n        stroke_linejoin,\n        class,\n    }} = props;\n\n"
    ));
    output.push_str("    rsx! {\n");
    push_svg_rsx(&mut output, icon);
    output.push_str("    }\n");
    output.push_str("}\n");

    output
}

fn push_doc_comment(output: &mut String, icon: &Icon, related_icons: &[&Icon]) {
    output.push_str(&format!("/// # {}\n", icon.component));
    output.push_str("///\n");
    output.push_str("/// ");
    output.push_str(&preview_img(icon, 48));
    output.push('\n');
    output.push_str("///\n");
    output.push_str("/// ");
    output.push_str(&widget_container(icon));
    output.push('\n');
    output.push_str("///\n");
    output.push_str("/// ## Tags\n");
    output.push_str("/// ");
    output.push_str(&join_or_dash(&icon.tags));
    output.push('\n');
    output.push_str("///\n");
    output.push_str("/// ## Categories\n");
    output.push_str("/// ");
    output.push_str(&join_or_dash(&icon.categories));
    output.push('\n');
    output.push_str("///\n");
    output.push_str("/// ## Source\n");
    output.push_str(&format!(
        "/// [Lucide v{LUCIDE_VERSION}](https://lucide.dev/icons/{})\n",
        icon.source_name
    ));
    output.push_str("///\n");
    output.push_str("/// ## Example\n");
    output.push_str("/// ```rust\n");
    output.push_str("/// use dioxus::prelude::*;\n");
    output.push_str(&format!(
        "/// use dioxus_icons::lucide::{};\n",
        icon.component
    ));
    output.push_str("///\n");
    output.push_str("/// fn app() -> Element {\n");
    output.push_str("///     rsx! {\n");
    output.push_str(&format!(
        "///         {} {{ size: 20, color: \"red\" }}\n",
        icon.component
    ));
    output.push_str("///     }\n");
    output.push_str("/// }\n");
    output.push_str("/// ```\n");
    if !related_icons.is_empty() {
        output.push_str("///\n");
        output.push_str("/// ## Related Icons\n");
        output.push_str("///\n");
        output.push_str("/// ");
        output.push_str(&related_icon_links(related_icons));
        output.push('\n');
    }
}

fn push_svg_rsx(output: &mut String, icon: &Icon) {
    let dom =
        dioxus_rsx_rosetta::Dom::parse(&icon.svg).expect("parsing SVG through dioxus-rsx-rosetta");
    let mut call_body = dioxus_rsx_rosetta::rsx_from_html(&dom);
    let svg = call_body
        .body
        .roots
        .iter_mut()
        .find_map(|node| match node {
            BodyNode::Element(element) => Some(element),
            _ => None,
        })
        .expect("rosetta SVG output should contain an element root");

    svg.raw_attributes = root_svg_attrs(&icon.view_box);
    svg.merged_attributes = svg.raw_attributes.clone();
    svg.spreads.clear();

    let rsx = dioxus_autofmt::write_block_out(&call_body).expect("formatting rosetta SVG as RSX");
    let rsx = rsx.trim_matches(['\r', '\n']);
    let base_indent = rsx
        .lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| line.len() - line.trim_start().len())
        .min()
        .unwrap_or_default();
    for line in rsx.lines() {
        output.push_str("        ");
        output.push_str(line.get(base_indent..).unwrap_or(line));
        output.push('\n');
    }
}

fn join_or_dash(values: &[String]) -> String {
    if values.is_empty() {
        "-".to_owned()
    } else {
        values
            .iter()
            .map(|value| markdown_text(value))
            .collect::<Vec<_>>()
            .join(", ")
    }
}

fn root_svg_attrs(view_box: &str) -> Vec<Attribute> {
    vec![
        rsx_lit_attr("xmlns", "http://www.w3.org/2000/svg"),
        rsx_lit_attr("width", "{size}"),
        rsx_lit_attr("height", "{size}"),
        rsx_lit_attr("view_box", view_box),
        rsx_lit_attr("fill", "none"),
        rsx_lit_attr("stroke", "{color}"),
        rsx_lit_attr("stroke_width", "{stroke_width}"),
        rsx_lit_attr("stroke_linecap", "{stroke_linecap}"),
        rsx_lit_attr("stroke_linejoin", "{stroke_linejoin}"),
        rsx_expr_attr(
            "class",
            "if class.is_empty() { None } else { Some(class.as_ref()) }",
        ),
    ]
}

fn rsx_lit_attr(name: &str, value: &str) -> Attribute {
    rsx_attr(
        name,
        AttributeValue::AttrLiteral(HotLiteral::from_raw_text(value)),
    )
}

fn rsx_expr_attr(name: &str, value: &str) -> Attribute {
    rsx_attr(
        name,
        AttributeValue::AttrExpr(PartialExpr {
            brace: None,
            expr: value.parse().expect("parsing generated RSX expression"),
        }),
    )
}

fn rsx_attr(name: &str, value: AttributeValue) -> Attribute {
    Attribute::from_raw(
        AttributeName::BuiltIn(Ident::new(name, Span::call_site())),
        value,
    )
}

fn markdown_text(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('[', "\\[")
        .replace(']', "\\]")
}
