use crate::fetch::LUCIDE_VERSION;
use crate::parse::{Icon, SvgElement};

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD;

pub fn emit_static_picker(icons: &[Icon]) -> String {
    let mut output = String::new();
    output.push_str(
        "<style>
.dioxus-icons-static-picker {
  margin: 24px 0;
  font-family: ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif;
  -webkit-font-smoothing: antialiased;
}
.dioxus-icons-static-picker p {
  color: var(--right-side-color, #888);
}
.dioxus-icons-static-picker h3 {
  margin: 22px 0 10px;
}
.dioxus-icons-static-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(96px, 1fr));
  gap: 4px;
}
.dioxus-icons-static-cell {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  min-height: 92px;
  padding: 8px 4px 10px;
  box-sizing: border-box;
  border-radius: 5px;
  color: inherit;
  text-align: center;
  text-decoration: none;
}
.dioxus-icons-static-cell:hover {
  color: var(--link-color, #3873ad);
  text-decoration: none;
}
.dioxus-icons-static-cell svg {
  width: 24px;
  height: 24px;
  flex: none;
}
.dioxus-icons-static-cell span {
  width: 100%;
  font-size: 11px;
  line-height: 1.3;
  color: var(--right-side-color, #888);
  overflow-wrap: anywhere;
}
.dioxus-icons-static-cell:hover span {
  color: var(--link-color, inherit);
}
@media (max-width: 640px) {
  .dioxus-icons-static-grid { grid-template-columns: repeat(auto-fill, minmax(80px, 1fr)); }
}
</style>
",
    );
    output.push_str(
        "<section id=\"dioxus-icons-static-picker\" class=\"dioxus-icons-static-picker\">\n",
    );
    output.push_str("<h2>Icon Index</h2>\n");
    output.push_str("<p>Browse by icon name, Lucide tags, or category.</p>\n");

    let mut current_group = '\0';
    for icon in icons {
        let group = icon
            .component
            .chars()
            .next()
            .unwrap_or('#')
            .to_ascii_uppercase();
        if group != current_group {
            if current_group != '\0' {
                output.push_str("</div>\n");
            }
            current_group = group;
            output.push_str(&format!("<h3>{group}</h3>\n"));
            output.push_str("<div class=\"dioxus-icons-static-grid\">\n");
        }

        output.push_str(&format!(
            "<a class=\"dioxus-icons-static-cell\" href=\"lucide/fn.{}.html\" title=\"{}\">",
            html_attr(&icon.component),
            html_attr(&search_text(icon))
        ));
        output.push_str(&preview_svg(icon, 24));
        output.push_str("<span>");
        output.push_str(&html_text(&icon.component));
        output.push_str("</span></a>\n");
    }

    if current_group != '\0' {
        output.push_str("</div>\n");
    }

    output.push_str("</section>\n");
    output
}

pub fn emit_lucide_docs_header() -> String {
    format!("//! Lucide v{LUCIDE_VERSION} icons generated by dioxus-icons-codegen.\n//!\n")
}

pub fn widget_container(icon: &Icon) -> String {
    let default_preview = preview_img(icon, 24);
    let data_svg = html_attr(&preview_svg(icon, 24));
    let code = highlighted_rsx_snippet(&icon.component, "24", "#000000", "2");
    format!(
        "<div class=\"dioxus-icons-widget\" data-icon-name=\"{name}\" data-svg=\"{svg}\" data-size=\"24\" data-color=\"#000000\" data-stroke=\"2\">\
<div class=\"dioxus-icons-widget-header\">\
<div class=\"dioxus-icons-widget-preview\" data-di-preview=\"true\" aria-label=\"{label} preview\">{preview}</div>\
<div class=\"dioxus-icons-widget-controls\">\
<label><span class=\"dioxus-icons-widget-label\">Size</span><input data-di-size=\"true\" type=\"number\" min=\"1\" max=\"256\" value=\"24\"></label>\
<label><span class=\"dioxus-icons-widget-label\">Color</span><input data-di-color=\"true\" type=\"color\" value=\"#000000\"></label>\
<label><span class=\"dioxus-icons-widget-label\">Stroke</span><input data-di-stroke=\"true\" type=\"number\" min=\"1\" max=\"12\" value=\"2\"></label>\
</div>\
</div>\
<div class=\"dioxus-icons-widget-output\">\
{code}\
<button type=\"button\" class=\"dioxus-icons-widget-copy\" data-di-copy=\"true\" aria-label=\"Copy RSX snippet\"><span data-di-copy-icon=\"true\"></span><span data-di-copy-label=\"true\">Copy RSX</span></button>\
</div>\
</div>",
        name = html_attr(&icon.component),
        svg = data_svg,
        label = html_attr(&icon.component),
        preview = default_preview,
        code = code
    )
}

pub fn rsx_snippet(component: &str, size: &str, color: &str, stroke: &str) -> String {
    format!("{component} {{ size: {size}, color: \"{color}\", stroke_width: {stroke} }}")
}

fn highlighted_rsx_snippet(component: &str, size: &str, color: &str, stroke: &str) -> String {
    let snippet = rsx_snippet(component, size, color, stroke);
    let expected =
        format!("{component} {{ size: {size}, color: \"{color}\", stroke_width: {stroke} }}");
    debug_assert_eq!(snippet, expected);

    format!(
        "<pre class=\"dioxus-icons-widget-code dxc dxc-system dxc-system-light-github-light dxc-system-dark-github-dark\" data-language=\"rust\"><code data-di-code=\"true\">{tokens}</code></pre>",
        tokens = highlighted_rsx_snippet_tokens(component, size, color, stroke)
    )
}

fn highlighted_rsx_snippet_tokens(
    component: &str,
    size: &str,
    color: &str,
    stroke: &str,
) -> String {
    format!(
        "<span class=\"a-t\">{component}</span><span> </span><span class=\"a-p\">{{</span><span> </span><span class=\"a-pr\">size</span><span class=\"a-p\">:</span><span> </span><span class=\"a-co\">{size}</span><span class=\"a-p\">,</span><span> </span><span class=\"a-pr\">color</span><span class=\"a-p\">:</span><span> </span><span class=\"a-s\">&quot;{color}&quot;</span><span class=\"a-p\">,</span><span> </span><span class=\"a-pr\">stroke_width</span><span class=\"a-p\">:</span><span> </span><span class=\"a-co\">{stroke}</span><span> </span><span class=\"a-p\">}}</span>",
        component = html_text(component),
        size = html_text(size),
        color = html_text(color),
        stroke = html_text(stroke)
    )
}

pub fn related_icon_links(icons: &[&Icon]) -> String {
    let mut output = String::new();
    output.push_str("<div class=\"dioxus-icons-related\">");

    for icon in icons {
        output.push_str(&format!(
            "<a class=\"dioxus-icons-related-link\" href=\"fn.{}.html\" title=\"{}\">",
            html_attr(&icon.component),
            html_attr(&icon.component)
        ));
        output.push_str(&preview_img(icon, 20));
        output.push_str("<span>");
        output.push_str(&html_text(&icon.component));
        output.push_str("</span></a>");
    }

    output.push_str("</div>");
    output
}

pub fn preview_img(icon: &Icon, size: u32) -> String {
    let svg = preview_svg(icon, size);
    format!(
        "<img src=\"{}\" alt=\"{} icon\">",
        html_attr(&svg_data_uri(&svg)),
        html_attr(&icon.component)
    )
}

pub fn preview_svg(icon: &Icon, size: u32) -> String {
    let mut svg = format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{size}\" height=\"{size}\" viewBox=\"{}\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">",
        html_attr(&icon.view_box)
    );

    for element in &icon.elements {
        push_svg_element(&mut svg, element);
    }

    svg.push_str("</svg>");
    svg
}

fn svg_data_uri(svg: &str) -> String {
    format!("data:image/svg+xml;base64,{}", STANDARD.encode(svg))
}

fn push_svg_element(output: &mut String, element: &SvgElement) {
    output.push('<');
    output.push_str(&element.tag);
    for (name, value) in &element.attrs {
        output.push(' ');
        output.push_str(name);
        output.push_str("=\"");
        output.push_str(&html_attr(value));
        output.push('"');
    }
    output.push_str("></");
    output.push_str(&element.tag);
    output.push('>');
}

fn search_text(icon: &Icon) -> String {
    let mut values = Vec::new();
    values.push(icon.component.clone());
    values.extend(icon.tags.clone());
    values.extend(icon.categories.clone());
    values.join(" ")
}

fn html_text(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn html_attr(value: &str) -> String {
    html_text(value).replace('"', "&quot;")
}
