use crate::fetch::{LUCIDE_COMMIT, LUCIDE_VERSION};
use crate::parse::{Icon, SvgElement};

use crate::emit_docs::{preview_img, widget_container};

pub fn emit_component(icon: &Icon) -> String {
    let mut output = String::new();

    output.push_str(&format!(
        "// @generated by dioxus-icons-codegen from Lucide v{LUCIDE_VERSION} ({LUCIDE_COMMIT}). Do not edit.\n"
    ));
    output.push_str("// Lucide icons are licensed under ISC. See LICENSE-LUCIDE.\n\n");
    output.push_str("use dioxus::prelude::*;\n");
    output.push('\n');

    let props_name = format!("{}Props", icon.component);

    output.push_str(&format!("/// Props for [`{}()`].\n", icon.component));
    output.push_str("#[derive(Clone, PartialEq, Props)]\n");
    output.push_str(&format!("pub struct {props_name} {{\n"));
    output.push_str("    /// SVG width and height in pixels.\n");
    output.push_str("    #[props(default = 24)]\n");
    output.push_str("    pub size: u32,\n");
    output.push_str("    /// SVG stroke color. Defaults to `currentColor`.\n");
    output.push_str("    #[props(into, default = \"currentColor\")]\n");
    output.push_str("    pub color: std::borrow::Cow<'static, str>,\n");
    output.push_str("    /// SVG stroke width.\n");
    output.push_str("    #[props(default = 2)]\n");
    output.push_str("    pub stroke_width: u32,\n");
    output.push_str("    /// SVG stroke linecap.\n");
    output.push_str("    #[props(into, default = \"round\")]\n");
    output.push_str("    pub stroke_linecap: std::borrow::Cow<'static, str>,\n");
    output.push_str("    /// SVG stroke linejoin.\n");
    output.push_str("    #[props(into, default = \"round\")]\n");
    output.push_str("    pub stroke_linejoin: std::borrow::Cow<'static, str>,\n");
    output.push_str("    /// CSS class for the root SVG. Empty by default.\n");
    output.push_str("    #[props(into, default = \"\")]\n");
    output.push_str("    pub class: std::borrow::Cow<'static, str>,\n");
    output.push_str("}\n\n");

    push_doc_comment(&mut output, icon);
    output.push_str("#[doc = include_str!(\"../../../rustdoc-header.html\")]\n");
    output.push_str("#[allow(non_snake_case)]\n");
    output.push_str("#[allow(clippy::too_many_lines)]\n");
    output.push_str(&format!(
        "pub fn {}(props: {props_name}) -> Element {{\n",
        icon.component
    ));
    output.push_str(&format!(
        "    let {props_name} {{\n        size,\n        color,\n        stroke_width,\n        stroke_linecap,\n        stroke_linejoin,\n        class,\n    }} = props;\n\n"
    ));
    output.push_str("    rsx! {\n");
    output.push_str("        svg {\n");
    output.push_str("            xmlns: \"http://www.w3.org/2000/svg\",\n");
    output.push_str("            width: \"{size}\",\n");
    output.push_str("            height: \"{size}\",\n");
    output.push_str("            view_box: \"0 0 24 24\",\n");
    output.push_str("            fill: \"none\",\n");
    output.push_str("            stroke: \"{color}\",\n");
    output.push_str("            stroke_width: \"{stroke_width}\",\n");
    output.push_str("            stroke_linecap: \"{stroke_linecap}\",\n");
    output.push_str("            stroke_linejoin: \"{stroke_linejoin}\",\n");
    output.push_str(
        "            class: if class.is_empty() { None } else { Some(class.as_ref()) },\n",
    );

    for element in &icon.elements {
        push_rsx_element(&mut output, element);
    }

    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("}\n");

    output
}

fn push_doc_comment(output: &mut String, icon: &Icon) {
    output.push_str(&format!("/// # {}\n", icon.component));
    output.push_str("///\n");
    output.push_str("/// ");
    output.push_str(&preview_img(icon, 48));
    output.push('\n');
    output.push_str("///\n");
    output.push_str("/// ## Sizes\n");
    output.push_str("/// ");
    output.push_str(&preview_img(icon, 16));
    output.push(' ');
    output.push_str(&preview_img(icon, 24));
    output.push(' ');
    output.push_str(&preview_img(icon, 32));
    output.push('\n');
    output.push_str("///\n");
    output.push_str("/// ## Tags\n");
    output.push_str("/// ");
    output.push_str(&join_or_dash(&icon.tags));
    output.push('\n');
    output.push_str("///\n");
    output.push_str("/// ## Categories\n");
    output.push_str("/// ");
    output.push_str(&join_or_dash(&icon.categories));
    output.push('\n');
    output.push_str("///\n");
    output.push_str("/// ## Source\n");
    output.push_str(&format!(
        "/// [Lucide v{LUCIDE_VERSION}](https://lucide.dev/icons/{})\n",
        icon.source_name
    ));
    output.push_str("///\n");
    output.push_str("/// ## Example\n");
    output.push_str("/// ```rust\n");
    output.push_str("/// use dioxus::prelude::*;\n");
    output.push_str(&format!(
        "/// use dioxus_icons::lucide::{};\n",
        icon.component
    ));
    output.push_str("///\n");
    output.push_str("/// fn app() -> Element {\n");
    output.push_str("///     rsx! {\n");
    output.push_str(&format!(
        "///         {} {{ size: 20, color: \"red\" }}\n",
        icon.component
    ));
    output.push_str("///     }\n");
    output.push_str("/// }\n");
    output.push_str("/// ```\n");
    output.push_str("///\n");
    output.push_str("/// ## Tweak\n");
    output.push_str("///\n");
    output.push_str("/// ");
    output.push_str(&widget_container(icon));
    output.push('\n');
}

fn push_rsx_element(output: &mut String, element: &SvgElement) {
    output.push_str("            ");
    output.push_str(&element.tag);
    output.push_str(" {\n");

    for (name, value) in &element.attrs {
        output.push_str("                ");
        output.push_str(&dioxus_attr_name(name));
        output.push_str(": ");
        output.push_str(&rust_string(value));
        output.push_str(",\n");
    }

    output.push_str("            }\n");
}

fn dioxus_attr_name(name: &str) -> String {
    match name {
        "viewBox" => "view_box".to_owned(),
        _ => name.replace('-', "_"),
    }
}

fn join_or_dash(values: &[String]) -> String {
    if values.is_empty() {
        "-".to_owned()
    } else {
        values
            .iter()
            .map(|value| markdown_text(value))
            .collect::<Vec<_>>()
            .join(", ")
    }
}

fn rust_string(value: &str) -> String {
    serde_json::to_string(value).expect("serializing string literal")
}

fn markdown_text(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('[', "\\[")
        .replace(']', "\\]")
}
