use anyhow::{Result, bail};

use crate::emit_docs::{preview_img, related_icon_links, widget_container};
use crate::fetch::{LUCIDE_COMMIT, LUCIDE_VERSION};
use crate::parse::{Icon, SvgElement};

pub fn emit_component(icon: &Icon) -> Result<String> {
    let mut output = String::new();

    output.push_str(&format!(
        "// @generated by dioxus-icons-codegen from Lucide v{LUCIDE_VERSION} ({LUCIDE_COMMIT}). Do not edit.\n"
    ));
    output.push_str("// Lucide icons are licensed under ISC. See LICENSE-LUCIDE.\n\n");
    if has_default_view_box(icon) {
        output.push_str("use dioxus::core::{Element, Template, TemplateNode};\n\n");
    } else {
        output.push_str(
            "use dioxus::core::{Element, Template, TemplateAttribute, TemplateNode};\n\n",
        );
    }
    output.push_str(&format!(
        "use crate::vdom::{{{}}};\n",
        vdom_imports(icon).join(", ")
    ));
    output.push_str("use crate::IconProps;\n\n");

    output.push_str(&format!(
        "#[cfg_attr(any(doc, rust_analyzer), doc = include_str!(\"docs/{}.md\"))]\n",
        icon.module
    ));
    output.push_str(
        "#[cfg_attr(any(doc, rust_analyzer), doc = include_str!(\"../../../rustdoc-header.html\"))]\n",
    );
    output.push_str("#[allow(non_snake_case)]\n");
    output.push_str(&format!(
        "pub fn {}(props: IconProps) -> Element {{\n",
        icon.component
    ));
    if has_default_view_box(icon) {
        output.push_str("    static TEMPLATE_ROOTS: &[TemplateNode] = &[svg(&[\n");
    } else {
        output.push_str("    static SVG_ATTRS: [TemplateAttribute; 1] = svg_attrs();\n");
        output.push_str(
            "    static TEMPLATE_ROOTS: &[TemplateNode] = &[svg_with_attrs(&SVG_ATTRS, &[\n",
        );
    }
    for element in &icon.elements {
        output.push_str(&emit_svg_element(element, 8)?);
    }
    output.push_str("    ])];\n");
    output.push_str("    static TEMPLATE: Template = icon_template(TEMPLATE_ROOTS);\n\n");
    output.push_str(&format!(
        "    icon_element(TEMPLATE, {}, props)\n",
        rust_str(&icon.view_box)
    ));
    output.push_str("}\n");

    Ok(output)
}

fn vdom_imports(icon: &Icon) -> Vec<&'static str> {
    let mut imports = vec!["attr"];
    for tag in [
        "circle", "ellipse", "line", "path", "polygon", "polyline", "rect",
    ] {
        if icon.elements.iter().any(|element| element.tag == tag) {
            imports.push(tag);
        }
    }
    imports.extend(["icon_element", "icon_template"]);
    if has_default_view_box(icon) {
        imports.push("svg");
    } else {
        imports.extend(["svg_attrs", "svg_with_attrs"]);
    }
    imports
}

fn has_default_view_box(icon: &Icon) -> bool {
    icon.view_box == "0 0 24 24"
}

pub fn emit_component_docs(icon: &Icon, related_icons: &[&Icon]) -> String {
    let mut output = String::new();
    output.push_str(&format!("# {}\n\n", icon.component));
    output.push_str(&preview_img(icon, 48));
    output.push_str("\n\n");
    output.push_str(&widget_container(icon));
    output.push_str("\n\n## Example\n");
    output.push_str("```rust\n");
    output.push_str("use dioxus::prelude::*;\n");
    output.push_str(&format!(
        "use dioxus_icons::lucide::{};\n\n",
        icon.component
    ));
    output.push_str("fn app() -> Element {\n");
    output.push_str("    rsx! {\n");
    output.push_str(&format!(
        "        {} {{ size: 20, stroke: \"red\" }}\n",
        icon.component
    ));
    output.push_str("    }\n");
    output.push_str("}\n");
    output.push_str("```\n");
    output.push_str("\n## Tags\n");
    output.push_str(&join_or_dash(&icon.tags));
    output.push_str("\n\n## Categories\n");
    output.push_str(&join_or_dash(&icon.categories));
    output.push_str("\n\n## Source\n");
    output.push_str(&format!(
        "[Lucide v{LUCIDE_VERSION}](https://lucide.dev/icons/{})\n",
        icon.source_name
    ));
    if !related_icons.is_empty() {
        output.push_str("\n## Related Icons\n\n");
        output.push_str(&related_icon_links(related_icons));
        output.push('\n');
    }
    output
}

fn emit_svg_element(element: &SvgElement, indent: usize) -> Result<String> {
    match element.tag.as_str() {
        "path" => {
            check_attrs(element, &["d", "fill"])?;
            emit_element(element, indent)
        }
        "circle" => {
            check_attrs(element, &["cx", "cy", "r", "fill"])?;
            emit_element(element, indent)
        }
        "rect" => {
            check_attrs(element, &["width", "height", "x", "y", "rx", "ry", "fill"])?;
            emit_element(element, indent)
        }
        "line" => {
            check_attrs(element, &["x1", "y1", "x2", "y2", "fill"])?;
            emit_element(element, indent)
        }
        "polyline" => {
            check_attrs(element, &["points", "fill"])?;
            emit_element(element, indent)
        }
        "polygon" => {
            check_attrs(element, &["points", "fill"])?;
            emit_element(element, indent)
        }
        "ellipse" => {
            check_attrs(element, &["cx", "cy", "rx", "ry", "fill"])?;
            emit_element(element, indent)
        }
        tag => bail!("unsupported SVG child tag `{tag}`"),
    }
}

fn emit_element(element: &SvgElement, indent: usize) -> Result<String> {
    let mut output = String::new();
    let spaces = " ".repeat(indent);
    output.push_str(&format!("{spaces}{}(&[\n", element.tag));
    for (name, value) in &element.attrs {
        output.push_str(&format!(
            "{spaces}    attr({}, {}),\n",
            rust_str(name),
            rust_str(value)
        ));
    }
    output.push_str(&format!("{spaces}]),\n"));
    Ok(output)
}

fn check_attrs(element: &SvgElement, allowed: &[&str]) -> Result<()> {
    for attr in element.attrs.keys() {
        if !allowed.contains(&attr.as_str()) {
            bail!("unsupported SVG attribute `{}` on <{}>", attr, element.tag);
        }
    }
    Ok(())
}

fn rust_str(value: &str) -> String {
    format!("{value:?}")
}

fn join_or_dash(values: &[String]) -> String {
    if values.is_empty() {
        "-".to_owned()
    } else {
        values
            .iter()
            .map(|value| markdown_text(value))
            .collect::<Vec<_>>()
            .join(", ")
    }
}

fn markdown_text(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('[', "\\[")
        .replace(']', "\\]")
}
