mod emit_component;
mod emit_docs;
mod emit_manifest;
mod fetch;
mod naming;
mod parse;
mod related;

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};

use crate::emit_component::emit_component;
use crate::emit_docs::{emit_lucide_docs_header, emit_static_picker};
use crate::emit_manifest::emit_manifest;
use crate::fetch::{LUCIDE_VERSION, ensure_lucide};
use crate::naming::icon_names;
use crate::parse::{Icon, parse_icon};
use crate::related::RelatedIcons;

fn main() -> Result<()> {
    if std::env::args().any(|arg| arg == "--check-lucide-updates") {
        return fetch::check_lucide_updates();
    }

    let workspace_root = workspace_root()?;
    let icons_dir = ensure_lucide(&workspace_root)?;
    let icons = read_icons(&icons_dir)?;
    let related_icons = RelatedIcons::load_lucide(&icons)?;
    let icons_by_source_name = icons
        .iter()
        .map(|icon| (icon.source_name.as_str(), icon))
        .collect::<BTreeMap<_, _>>();

    let generated_dir = workspace_root.join("crates/dioxus-icons/src/generated");
    let lucide_dir = generated_dir.join("lucide");
    reset_dir(&lucide_dir)?;

    for icon in &icons {
        let component_path = lucide_dir.join(format!("{}.rs", icon.module));
        let related = related_icons.for_icon(icon, &icons_by_source_name)?;
        fs::write(&component_path, emit_component(icon, &related))
            .with_context(|| format!("writing {}", component_path.display()))?;
    }

    fs::write(generated_dir.join("mod.rs"), emit_generated_mod())?;
    fs::write(lucide_dir.join("mod.rs"), emit_lucide_mod(&icons))?;
    fs::write(generated_dir.join("manifest.json"), emit_manifest(&icons)?)?;
    fs::write(
        workspace_root.join("crates/dioxus-icons/STATIC_PICKER.html"),
        emit_static_picker(&icons),
    )?;

    rustfmt_generated(&generated_dir, &lucide_dir, &icons)?;

    println!(
        "generated {} Lucide v{} icons into {}",
        icons.len(),
        LUCIDE_VERSION,
        generated_dir.display()
    );

    Ok(())
}

fn workspace_root() -> Result<PathBuf> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .context("finding workspace root from CARGO_MANIFEST_DIR")
}

fn read_icons(icons_dir: &Path) -> Result<Vec<Icon>> {
    let mut svg_paths = fs::read_dir(icons_dir)
        .with_context(|| format!("reading {}", icons_dir.display()))?
        .map(|entry| entry.map(|entry| entry.path()))
        .collect::<Result<Vec<_>, _>>()?
        .into_iter()
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("svg"))
        .collect::<Vec<_>>();

    svg_paths.sort();

    let mut icons = Vec::with_capacity(svg_paths.len());
    let mut components = BTreeSet::new();
    let mut modules = BTreeSet::new();

    for svg_path in svg_paths {
        let stem = svg_path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .with_context(|| format!("invalid SVG file name {}", svg_path.display()))?;
        let json_path = icons_dir.join(format!("{stem}.json"));
        if !json_path.exists() {
            bail!("missing metadata sidecar {}", json_path.display());
        }

        let names = icon_names(stem)?;
        if !components.insert(names.component.clone()) {
            bail!("duplicate generated component `{}`", names.component);
        }
        if !modules.insert(names.module.clone()) {
            bail!("duplicate generated module `{}`", names.module);
        }

        icons.push(parse_icon(&svg_path, &json_path, names)?);
    }

    Ok(icons)
}

fn reset_dir(path: &Path) -> Result<()> {
    if path.exists() {
        fs::remove_dir_all(path).with_context(|| format!("removing {}", path.display()))?;
    }
    fs::create_dir_all(path).with_context(|| format!("creating {}", path.display()))?;
    Ok(())
}

fn emit_generated_mod() -> String {
    "// @generated by dioxus-icons-codegen. Do not edit.\n\npub mod lucide;\n".to_owned()
}

fn emit_lucide_mod(icons: &[Icon]) -> String {
    let mut output = String::new();
    output.push_str(&emit_lucide_docs_header());
    output.push_str("// @generated by dioxus-icons-codegen. Do not edit.\n\n");

    for icon in icons {
        output.push_str(&format!("pub mod {};\n", icon.module_ref));
    }

    output.push('\n');

    for icon in icons {
        output.push_str(&format!(
            "pub use {}::{};\n",
            icon.module_ref, icon.component
        ));
    }

    output
}

fn rustfmt_generated(generated_dir: &Path, lucide_dir: &Path, icons: &[Icon]) -> Result<()> {
    let mut files = Vec::with_capacity(icons.len() + 2);
    files.push(generated_dir.join("mod.rs"));
    files.push(lucide_dir.join("mod.rs"));
    files.extend(
        icons
            .iter()
            .map(|icon| lucide_dir.join(format!("{}.rs", icon.module))),
    );

    let status = Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .args(&files)
        .status()
        .context("running rustfmt over generated Rust files")?;

    if !status.success() {
        bail!("rustfmt failed with status {status}");
    }

    Ok(())
}
