mod emit_component;
mod emit_docs;
mod emit_manifest;
mod fetch;
mod inputs;
mod naming;
mod parse;
mod related;

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};

use crate::emit_component::{emit_component, emit_component_docs};
use crate::emit_docs::{emit_lucide_docs_header, emit_static_picker};
use crate::emit_manifest::emit_manifest;
use crate::fetch::{LUCIDE_VERSION, ensure_lucide};
use crate::naming::icon_names;
use crate::parse::{Icon, parse_icon};
use crate::related::RelatedIcons;

fn main() -> Result<()> {
    if std::env::args().any(|arg| arg == "--check-lucide-updates") {
        return fetch::check_lucide_updates();
    }

    let workspace_root = workspace_root()?;
    let icons_dir = ensure_lucide(&workspace_root)?;
    let icons = read_icons(&icons_dir)?;
    let related_icons = RelatedIcons::load_lucide(&icons)?;
    let icons_by_source_name = icons
        .iter()
        .map(|icon| (icon.source_name.as_str(), icon))
        .collect::<BTreeMap<_, _>>();

    let generated_dir = workspace_root.join("crates/dioxus-icons/src/generated");
    let lucide_dir = generated_dir.join("lucide");
    let docs_dir = lucide_dir.join("docs");
    reset_dir(&lucide_dir)?;
    fs::create_dir_all(&docs_dir).with_context(|| format!("creating {}", docs_dir.display()))?;

    for icon in &icons {
        let component_path = lucide_dir.join(format!("{}.rs", icon.module));
        let docs_path = docs_dir.join(format!("{}.md", icon.module));
        let related = related_icons.for_icon(icon, &icons_by_source_name)?;
        fs::write(&component_path, emit_component(icon)?)
            .with_context(|| format!("writing {}", component_path.display()))?;
        fs::write(&docs_path, emit_component_docs(icon, &related))
            .with_context(|| format!("writing {}", docs_path.display()))?;
    }

    fs::write(generated_dir.join("mod.rs"), emit_generated_mod())?;
    fs::write(lucide_dir.join("mod.rs"), emit_lucide_mod(&icons))?;
    fs::write(generated_dir.join("manifest.json"), emit_manifest(&icons)?)?;
    fs::write(
        workspace_root.join("crates/dioxus-icons/STATIC_PICKER.html"),
        emit_static_picker(&icons),
    )?;

    rustfmt_generated(&generated_dir, &lucide_dir, &icons)?;

    fs::write(
        generated_dir.join("inputs_hash.txt"),
        format!("{}\n", inputs::compute_inputs_hash()?),
    )?;

    println!(
        "generated {} Lucide v{} icons into {}",
        icons.len(),
        LUCIDE_VERSION,
        generated_dir.display()
    );

    Ok(())
}

fn workspace_root() -> Result<PathBuf> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .context("finding workspace root from CARGO_MANIFEST_DIR")
}

fn read_icons(icons_dir: &Path) -> Result<Vec<Icon>> {
    let mut svg_paths = fs::read_dir(icons_dir)
        .with_context(|| format!("reading {}", icons_dir.display()))?
        .map(|entry| entry.map(|entry| entry.path()))
        .collect::<Result<Vec<_>, _>>()?
        .into_iter()
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("svg"))
        .collect::<Vec<_>>();

    svg_paths.sort();

    let mut icons = Vec::with_capacity(svg_paths.len());
    let mut components = BTreeSet::new();
    let mut modules = BTreeSet::new();

    for svg_path in svg_paths {
        let stem = svg_path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .with_context(|| format!("invalid SVG file name {}", svg_path.display()))?;
        let json_path = icons_dir.join(format!("{stem}.json"));
        if !json_path.exists() {
            bail!("missing metadata sidecar {}", json_path.display());
        }

        let names = icon_names(stem)?;
        if !components.insert(names.component.clone()) {
            bail!("duplicate generated component `{}`", names.component);
        }
        if !modules.insert(names.module.clone()) {
            bail!("duplicate generated module `{}`", names.module);
        }

        icons.push(parse_icon(&svg_path, &json_path, names)?);
    }

    Ok(icons)
}

fn reset_dir(path: &Path) -> Result<()> {
    if path.exists() {
        fs::remove_dir_all(path).with_context(|| format!("removing {}", path.display()))?;
    }
    fs::create_dir_all(path).with_context(|| format!("creating {}", path.display()))?;
    Ok(())
}

fn emit_generated_mod() -> String {
    "// @generated by dioxus-icons-codegen. Do not edit.\n\npub mod lucide;\n".to_owned()
}

fn emit_lucide_mod(icons: &[Icon]) -> String {
    let mut output = String::new();
    output.push_str(&emit_lucide_docs_header());
    output.push_str("// @generated by dioxus-icons-codegen. Do not edit.\n\n");

    for icon in icons {
        output.push_str(&format!("pub mod {};\n", icon.module_ref));
    }

    output.push('\n');

    for icon in icons {
        output.push_str(&format!(
            "pub use {}::{};\n",
            icon.module_ref, icon.component
        ));
    }

    output
}

fn rustfmt_generated(generated_dir: &Path, lucide_dir: &Path, icons: &[Icon]) -> Result<()> {
    let mut files = Vec::with_capacity(icons.len() + 2);
    files.push(generated_dir.join("mod.rs"));
    files.push(lucide_dir.join("mod.rs"));
    files.extend(
        icons
            .iter()
            .map(|icon| lucide_dir.join(format!("{}.rs", icon.module))),
    );

    let status = Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .args(&files)
        .status()
        .context("running rustfmt over generated Rust files")?;

    if !status.success() {
        bail!("rustfmt failed with status {status}");
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixture_codegen_covers_parser_naming_manifest_docs_and_component_emission() {
        let icons = read_icons(&fixture_icons_dir()).expect("reading fixture icons");

        assert_eq!(
            icons
                .iter()
                .map(|icon| format!(
                    "{}:{}:{}",
                    icon.source_name, icon.module_ref, icon.component
                ))
                .collect::<Vec<_>>(),
            [
                "1-circle:circle_1:Circle1",
                "box:r#box:Box",
                "trash-2:trash_2:Trash2"
            ]
        );
        assert_eq!(icons[0].view_box, "0 0 24 24");
        assert_eq!(icons[0].elements[0].tag, "circle");
        assert_eq!(icons[0].tags, ["number", "status"]);
        assert_eq!(icons[0].categories, ["shapes"]);

        let manifest_json = emit_manifest(&icons).expect("emitting manifest");
        assert!(manifest_json.contains("\\u003csvg"));
        assert!(!manifest_json.contains("<svg"));

        let manifest: serde_json::Value =
            serde_json::from_str(&manifest_json).expect("parsing manifest");
        assert_eq!(manifest["version"], LUCIDE_VERSION);
        assert_eq!(manifest["source"], "lucide");
        assert_eq!(manifest["icons"].as_array().unwrap().len(), 3);
        assert_eq!(manifest["icons"][0]["name"], "Circle1");
        assert_eq!(manifest["icons"][0]["module"], "circle_1");
        assert_eq!(manifest["icons"][0]["tags"][0], "number");
        assert_eq!(manifest["icons"][1]["name"], "Box");
        assert_eq!(manifest["icons"][2]["categories"][0], "actions");

        let docs = emit_static_picker(&icons);
        assert!(docs.contains("href=\"lucide/fn.Circle1.html\""));
        assert!(docs.contains("title=\"Circle1 number status shapes\""));
        assert!(docs.contains("<span>Trash2</span>"));

        let lucide_mod = emit_lucide_mod(&icons);
        assert!(lucide_mod.contains("pub mod circle_1;"));
        assert!(lucide_mod.contains("pub mod r#box;"));
        assert!(lucide_mod.contains("pub use circle_1::Circle1;"));
        assert!(lucide_mod.contains("pub use r#box::Box;"));

        let component = emit_component(&icons[0]).expect("emitting component");
        assert!(!component.contains("pub struct Circle1Props"));
        assert!(component.contains("pub fn Circle1(props: IconProps) -> Element"));
        assert!(!component.contains("rsx! {"));
        assert!(component.contains("static TEMPLATE_ROOTS: &[TemplateNode]"));
        assert!(!component.contains("TemplateAttribute"));
        assert!(!component.contains("static SVG_ATTRS"));
        assert!(component.contains("svg(&["));
        assert!(component.contains("circle(&["));
        assert!(component.contains("attr(\"cx\", \"12\")"));
        assert!(component.contains("static TEMPLATE: Template = icon_template(TEMPLATE_ROOTS);"));
        assert!(component.contains("icon_element(TEMPLATE, \"0 0 24 24\", props)"));
        assert!(!component.contains("dynamic_attributes"));
        assert!(!component.contains("render_lucide_icon"));

        let mut non_default_view_box = icons[0].clone();
        non_default_view_box.view_box = "0 0 16 16".to_owned();
        let non_default_component =
            emit_component(&non_default_view_box).expect("emitting non-default viewBox component");
        assert!(non_default_component.contains("TemplateAttribute"));
        assert!(non_default_component.contains("TemplateAttribute; 1"));
        assert!(non_default_component.contains("svg_attrs()"));
        assert!(non_default_component.contains("svg_with_attrs(&SVG_ATTRS"));
        assert!(non_default_component.contains("icon_element(TEMPLATE, \"0 0 16 16\", props)"));

        let component_docs = emit_component_docs(&icons[0], &[&icons[1]]);
        assert!(component_docs.contains("use dioxus_icons::lucide::Circle1;"));
        assert!(component_docs.contains("dxc-system-light-github-light"));
        assert!(
            component_docs.contains("Circle1</span><span> </span><span class=\"a-p\">{</span>")
        );
        assert!(component_docs.contains("<span class=\"a-pr\">stroke_width</span>"));
        assert!(component_docs.contains("href=\"fn.Box.html\""));

        assert_eq!(
            crate::emit_docs::rsx_snippet("Trash", "24", "#000000", "2"),
            "Trash { size: 24, stroke: \"#000000\", stroke_width: 2 }"
        );
    }

    fn fixture_icons_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures/lucide-mini/icons")
    }
}
